#!/bin/bash

pytest --oof --oof-sut-id same-sut --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'
pytest --oof --oof-sut-id same-sut --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'
pytest --oof --oof-sut-id same-sut --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'pytest --oof --oof-sut-id 123e4567-e89b-12d3-a456-426614174000 --oof-sut-type PROD --oof-sut-version 1.0.0 --oof-sut-env 'gems-core (v7.10.0) | catl-battery (v7.5.0)'
pytest --oof --oof-sut-id sut-abc-123 --oof-sut-type DEV --oof-sut-version 1.1.0 --oof-sut-env 'gems-core (v7.11.0) | catl-battery (v7.6.0)'
pytest --oof --oof-sut-id qa-ref-openjdk17 --oof-sut-type QA --oof-sut-version 2.0.0 --oof-sut-env 'gems-core (v8.0.0) | gridsolv-quantum (v7.5.0)'
pytest --oof --oof-sut-id qa-ref-dist-core-openjdk17 --oof-sut-type BETA --oof-sut-version 2.0.1 --oof-sut-env 'gems-core (v9.0.0) | gridsolv-quantum (v7.6.0)'
pytest --oof --oof-sut-id sut-abc-123 --oof-sut-type PROD --oof-sut-version 1.2.0 --oof-sut-env 'gems-core (v7.12.0)'
pytest --oof --oof-sut-id sut-abc-123 --oof-sut-type STAGE --oof-sut-version 1.3.0 --oof-sut-env 'gems-core (v7.13.0)'
pytest --oof --oof-sut-id sut-abc-123 --oof-sut-type DEV --oof-sut-version 1.4.0 --oof-sut-env 'gems-core (v7.14.0)'
pytest --oof --oof-sut-id sut-abc-123 --oof-sut-type BETA --oof-sut-version 1.3.3 --oof-sut-env 'gems-core (v7.14.1)'
pytest --oof --oof-sut-id qa-ref-azulprimejdk17 --oof-sut-type PROD --oof-sut-version 2.1.0 --oof-sut-env 'gems-core (v8.1.0)'
pytest --oof --oof-sut-id qa-ref-openjdk17 --oof-sut-type PROD --oof-sut-version 2.2.0 --oof-sut-env 'gems-core (v8.2.0)'
pytest --oof --oof-sut-id qa-ref-dist-core-azulprimejdk17 --oof-sut-type PROD --oof-sut-version 2.3.0 --oof-sut-env 'gems-core (v8.3.0)'
pytest --oof --oof-sut-id qa-ref-dist-core-openjdk17 --oof-sut-type PROD --oof-sut-version 2.2.0 --oof-sut-env 'gems-core (v8.2.0)'
pytest --oof --oof-sut-id qa-ref-azulprimejdk17 --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'
pytest --oof --oof-sut-id qa-ref-openjdk17 --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'
pytest --oof --oof-sut-id qa-ref-dist-core-azulprimejdk17 --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'
pytest --oof --oof-sut-id qa-ref-dist-core-openjdk17 --oof-sut-type QA --oof-sut-version 3.0.0 --oof-sut-env 'gems-core (v9.0.0)'
